services:
  # our postgreSQL database
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: Sscl28@#$

  # The UI service
  ui:
    image: ghcr.io/devtiro/devtiro-build-task-app:latest
    ports:
      - "3000:3000"
    environment:
      - BACKEND_HOST=host.docker.internal
      - BACKEND_PORT=8082
    extra_hosts:
      - "host.docker.internal:host-gateway"